### ISSUE TITLE
trian code

### ISSUE THREAD

**Issue by YUPENG0423** [amao0o0/SynWMD#1]
I can't find your training code among your codes. Could you please provide me your training code?

**Comment by amao0o0** [comment]
Hi. SynWMD is an unsupervised method, so it doesn't require training.

**Comment by YUPENG0423** [comment]
Thank you for your answer. In my understanding, the unsupervised method is just different in the data preprocessing stage. I found the pre-trained kernel and bias for whitening in your code. Can you tell me where you got this document?

**Comment by amao0o0** [comment]
You can use [whiten.py](https://github.com/amao0o0/SynWMD/blob/main/whiten.py) to get the whitening pre-trained kernel and bias.
